[package]
name    = "kiss3d"
version = "0.6.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

description = "3D graphics engine for Rust."
repository = "https://github.com/sebcrozet/kiss3d"
readme = "README.md"
keywords = [ "3D", "graphics", "OpenGL", "KISS" ]
license = "BSD-3-Clause"

include = [
    "src/**/*.rs",
    "examples/**/*.rs",
    "examples/media",
    "examples/Cargo.toml",
    "Cargo.toml",
    "LICENSE",
    "Readme.md"
]

[lib]
name = "kiss3d"
path = "src/lib.rs"

[dependencies]
gl = "0.6.*"
glutin = "*"
image = "0.6.*"
libc = "0.2.*"
nalgebra = "0.9.*"
ncollide_procedural = "0.5.*"
num = "0.1.*"

[dev-dependencies]
rand = "0.3.*"
ncollide_transformation = "0.5.*"
